# Generated by Django 3.1.7 on 2021-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210302_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face',
            field=models.ImageField(default='face/defo.jpg', upload_to='face/'),
        ),
    ]
