# Generated by Django 3.1.7 on 2021-03-05 06:25

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210303_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face',
            field=models.ImageField(blank=True, default='face/defo.jpg', upload_to='face/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
