# Generated by Django 3.1.7 on 2021-03-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albam',
            name='art',
            field=models.ImageField(default='albam_art/defo.jpg', upload_to='albam_art/'),
        ),
    ]
