# Generated by Django 3.1.7 on 2021-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210303_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albam',
            name='art',
            field=models.ImageField(blank=True, default='albam_art/defo.jpg', upload_to='albam_art/'),
        ),
    ]
