# Generated by Django 3.1.7 on 2021-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210305_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='musicfile',
            field=models.FileField(default=99, upload_to='musicfile/'),
            preserve_default=False,
        ),
    ]
