# Generated by Django 3.1.7 on 2021-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_score_musicfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='art',
            field=models.ImageField(blank=True, default='score_art/defo.jpg', upload_to='score_art/'),
        ),
    ]
